### ISSUE TITLE
kiip.endSession hangs app if called before kiip.init

### ISSUE THREAD

**Issue by jhoff** [NinthDecimal/phonegap-plugin#1]
If the app is launched, and kiip.endSession is called before kiip.init, then the app will hang, timeout and cause a force close window.

While this is probably a corner case, I commonly see it when the user launches the app and quickly exits prior to deviceready.

I realize this can be avoided, but ideally, kiip.endSession should just return if kiip.init hasn't been called yet.

**Comment by nickhs** [comment]
Thanks for picking that up! I've just pushed a change (f9200c8) which should hopefully fix that. Please feel free to try it out and let me know if you're still having any trouble.
